installation:
  channel: stable
  installPlan: Automatic
CR:
  quay:
    persistentVolumeSize: 10
  db:
    volumeSize: 10
  clair:
    enabled: "false"
    updateInterval: "60m"
  secrets:
    quay:
      super:
        user: "cloudlet_admin"
        pass: "Password@123"
        mail: "quay@cloudlet.com"
      config:
        pass: "Password@123"
        user_autocomplete: false
        token_EXP: "3m"
        anonymous: false
        requrie_ENCRYP: true
        users_Creation: false
    redis:
      pass: "Password@123"
    db:
      user: "quaydb"
      pass: "Password@123"
      name: "quaydb"
