image:
  repository: quay.io/amitai333/sampleapp
  tag: latest

namespace: node-postgres

# DB VARS
pgcluster:
  PG_CLUSTER_NAME: "sampleapp"
  PG_NAMESPACE: "pgo"
  PG_PGO_VERSION: 4.3.0
  PG_STORAGE_CLASS: managed-premium
  PG_STORAGE_SIZE: 1G
  PG_IMAGE_NAME: crunchy-postgres-ha
  PG_IMAGE_TAG: centos7-12.2-4.3.0
  PG_DATABASE_NAME: sampledb
  PG_REPLICAS: "2"
  DB_USERNAME: myuser
  DB_PASSWORD: password