image:
  repository: registry.ocp43-prod.sales.lab.tlv.redhat.com:5000/rh-sso-7/sso74-openshift-rhel8
  tag: 7.4

pg_image:
  repository: registry.ocp43-prod.sales.lab.tlv.redhat.com:5000/rhel8/postgresql-10
  tag: latest

rhsso_namespace: rh-sso

APPLICATION_NAME: "sso"
SSO_HOSTNAME: ""
JGROUPS_CLUSTER_PASSWORD: "Aa123456"
DB_JNDI: "java:jboss/datasources/KeycloakDS"
DB_DATABASE: "root"
DB_USERNAME: "cloudlet"
DB_PASSWORD: "Aa123456"
VOLUME_CAPACITY: "1Gi"
SSO_ADMIN_USERNAME: "admin"
SSO_ADMIN_PASSWORD: "Aa123456"
SSO_REALM: ""
SSO_SERVICE_USERNAME: ""
SSO_SERVICE_PASSWORD: ""
MEMORY_LIMIT: "1Gi"
