apiVersion: v1
kind: Secret
data:
  DB_USERNAME: {{ index .Values "auth" "username" | toString | b64enc }}
  DB_PASSWORD: {{ index .Values "auth" "password" | toString | b64enc }}
metadata:
  name: node-secret
  namespace: {{ index .Values "global" "namespaceOverride" }}
type: Opaque