configmap:
  quay_repo_1: https://quay.apps
  quay_repo_2: cloudlet-dev.com
  splunk_event_url: https://13.90.23.80:8088/services/collector/event
  cluster_name: prod
  quay_token: m22zF0WNdB0apZXsURx5YNvyukGoaeMefCziaRWp
  splunk_token: 76dfd089-67f2-4262-978e-755af5c0775a

containers:
  repository: docker.io/meshistern
  image: quay-logs
  version: latest
