image:
  repository: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8
  tag: 7.4

rhsso_namespace: rh-sso

APPLICATION_NAME: "sso"
SSO_HOSTNAME: ""
JGROUPS_CLUSTER_PASSWORD: "Aa123456"
DB_JNDI: "java:jboss/datasources/KeycloakDS"
DB_DATABASE: "ssodb"
DB_USERNAME: "myuser"
DB_PASSWORD: "password"
VOLUME_CAPACITY: "1Gi"
SSO_ADMIN_USERNAME: "admin"
SSO_ADMIN_PASSWORD: "Aa123456"
SSO_REALM: ""
SSO_SERVICE_USERNAME: ""
SSO_SERVICE_PASSWORD: ""
MEMORY_LIMIT: "1Gi"
SSO_POSTGRESQL_PORT: "tcp://ssodb.pgo.svc.cluster.local:5432"
SSO_POSTGRESQL_PORT_5432_TCP: "tcp://ssodb.pgo.svc.cluster.local:5432"
SSO_POSTGRESQL_SERVICE_HOST: "ssodb.pgo.svc.cluster.local"
SSO_POSTGRESQL_PORT_5432_TCP_ADDR: "ssodb.pgo.svc.cluster.local"
HOSTNAME_HTTP: ""

HTTPS_SECRET: sso-app-secret 
HTTPS_KEYSTORE: keystore.jks
HTTPS_NAME: jboss
HTTPS_PASSWORD: redhat
JGROUPS_ENCRYPT_SECRET: sso-app-secret
JGROUPS_ENCRYPT_KEYSTORE: jgroups.jceks 
JGROUPS_ENCRYPT_NAME: secret-key
JGROUPS_ENCRYPT_PASSWORD: redhat
SSO_TRUSTSTORE: truststore.jks
SSO_TRUSTSTORE_PASSWORD: redhat
SSO_TRUSTSTORE_SECRET: sso-app-secret

# DB VARS
pgcluster:
  PG_CLUSTER_NAME: "ssodb"
  PG_NAMESPACE: "pgo"
  PG_PGO_VERSION: 4.3.0
  PG_STORAGE_CLASS: managed-premium
  PG_STORAGE_SIZE: 1G
  PG_IMAGE_NAME: crunchy-postgres-ha
  PG_IMAGE_TAG: centos7-12.2-4.3.0
  PG_DATABASE_NAME: ssodb
  PG_REPLICAS: "2"
  PG_SERVICE_PREFIX: "ssodb.pgo"