image:
  repository: meshistern
  name: argo-to-splunk
  tag: "latest"


conf: 
  argoUrl = 'https://argocd-argocd.apps.ocp43-prod.cloudlet-dev.com/'
  appsApi = 'api/v1/applications'
  authApi = 'api/v1/session'
  login = {"username": "admin", "password": "6KEgvtYJaRlbUT82reCWwA4mDinV3OoP"}
  splunkUrl = 'https://13.90.23.80:8088/services/collector/event'
  splunkAuth = {'Authorization': 'Splunk c92a548a-e243-41ab-9168-8a17ce013342'}
 
