image:
  repository: quay.io/amitai333/sampleapp2
  tag: latest

namespace: mongodb-clusters


# DB VARS
mongodb:
  APPLICATION_NAME: sampleapp
  auth:
    rootPassword: "admin"
    username: admin
    password: admin
    database: sampledb
  replicaSetName: rs0
  replicaCount: 3
  global:
    namespaceOverride: mongodb-clusters